import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font] 
  normal = { family = "FiraCode Nerd Font", style = "Regular" }
  size = 15.0


[window]
  decorations = "None"

# padding = { x = 3, y = 0 }

[scrolling]
  history = 5000


[env]
  TERM = "xterm-256color"

