# The definition of color schemes.
[colors.primary]
background = '0x1d2021'
foreground = '0xd4be98'
[colors.normal]
black =   '0x32302f'
red =     '0xea6962'
green =   '0xa9b665'
yellow =  '0xd8a657'
blue =    '0x7daea3'
magenta = '0xd3869b'
cyan =    '0x89b482'
white =   '0xd4be98'
[colors.bright]
black =   '0x32302f'
red =     '0xea6962'
green =   '0xa9b665'
yellow =  '0xd8a657'
blue =    '0x7daea3'
magenta = '0xd3869b'
cyan =    '0x89b482'
white =   '0xd4be98'
# gruvbox_material_medium_dark = &gruvbox_material_medium_dark
# [colors.primary] =
# background = '0x282828'
# foreground = '0xd4be98'
# [colors.normal]
# black =   '0x3c3836'
# red =     '0xea6962'
# green =   '0xa9b665'
# yellow =  '0xd8a657'
# blue =    '0x7daea3'
# magenta = '0xd3869b'
# cyan =    '0x89b482'
# white =   '0xd4be98'
# [colors.bright]
# black =   '0x3c3836'
# red =     '0xea6962'
# green =   '0xa9b665'
# yellow =  '0xd8a657'
# blue =    '0x7daea3'
# magenta = '0xd3869b'
# cyan =    '0x89b482'
# white =   '0xd4be98'
# gruvbox_material_soft_dark = &gruvbox_material_soft_dark
# [colors.primary] =
# background = '0x32302f'
# foreground = '0xd4be98'
# [colors.normal]
# black =   '0x45403d'
# red =     '0xea6962'
# green =   '0xa9b665'
# yellow =  '0xd8a657'
# blue =    '0x7daea3'
# magenta = '0xd3869b'
# cyan =    '0x89b482'
# white =   '0xd4be98'
# [colors.bright]
# black =   '0x45403d'
# red =     '0xea6962'
# green =   '0xa9b665'
# yellow =  '0xd8a657'
# blue =    '0x7daea3'
# magenta = '0xd3869b'
# cyan =    '0x89b482'
# white =   '0xd4be98'
# gruvbox_material_hard_light = &gruvbox_material_hard_light
# [colors.primary] =
# background = '0xf9f5d7'
# foreground = '0x654735'
# [colors.normal]
# black =   '0x654735'
# red =     '0xc14a4a'
# green =   '0x6c782e'
# yellow =  '0xb47109'
# blue =    '0x45707a'
# magenta = '0x945e80'
# cyan =    '0x4c7a5d'
# white =   '0xf2e5bc'
# [colors.bright]
# black =   '0x654735'
# red =     '0xc14a4a'
# green =   '0x6c782e'
# yellow =  '0xb47109'
# blue =    '0x45707a'
# magenta = '0x945e80'
# cyan =    '0x4c7a5d'
# white =   '0xf2e5bc'
# gruvbox_material_medium_light = &gruvbox_material_medium_light
# [colors.primary] =
# background = '0xfbf1c7'
# foreground = '0x654735'
# [colors.normal]
# black =   '0x654735'
# red =     '0xc14a4a'
# green =   '0x6c782e'
# yellow =  '0xb47109'
# blue =    '0x45707a'
# magenta = '0x945e80'
# cyan =    '0x4c7a5d'
# white =   '0xeee0b7'
# [colors.bright]
# black =   '0x654735'
# red =     '0xc14a4a'
# green =   '0x6c782e'
# yellow =  '0xb47109'
# blue =    '0x45707a'
# magenta = '0x945e80'
# cyan =    '0x4c7a5d'
# white =   '0xeee0b7'
# gruvbox_material_soft_light = &gruvbox_material_soft_light
# [colors.primary] =
# background = '0xf2e5bc'
# foreground = '0x654735'
# [colors.normal]
# black =   '0x654735'
# red =     '0xc14a4a'
# green =   '0x6c782e'
# yellow =  '0xb47109'
# blue =    '0x45707a'
# magenta = '0x945e80'
# cyan =    '0x4c7a5d'
# white =   '0xe6d5ae'
# [colors.bright]
# black =   '0x654735'
# red =     '0xc14a4a'
# green =   '0x6c782e'
# yellow =  '0xb47109'
# blue =    '0x45707a'
# magenta = '0x945e80'
# cyan =    '0x4c7a5d'
# white =   '0xe6d5ae'
# 
# # Apply the color scheme.
# colors = *gruvbox_material_medium_dark
